config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  resources :orders
  resources :users, except: [:user, :create]

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
    
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
 
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    # makes Current.user accessible in view files.
    attribute :user
  end

app/models/order.rb
class Order < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    
    def set_current_user
      # finds user with session data and stores it if present
      Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
    end
    def require_user_logged_in!
      # allows only logged in user
      redirect_to sign_in_path, alert: 'You must be signed in' if Current.user.nil?
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
      @orders = Order.all
    end
    def show
      @order = Order.find(params[:id])
    end

    def new
      @order = Order.new
    end
  
    def create
      @order = Order.new(order_params)
  
      if @order.save
        WelcomeMailer.with(order: @order).welcome_email.deliver_later
        OrderMailer.with(order: @order).new_order_email.deliver_later
        
        flash[:success] = "Thank you for your order! We'll get contact you soon!"
        redirect_to root_path
      else
        flash.now[:error] = "Your order form had some errors. Please check the form and resubmit."
        render :new
      end
    end
    def edit
      #byebug
      @order = Order.find(params[:id])
    end
    def update        
        @order = Order.find(params[:id])
        if @order.update(order_params)
            #byebug
            OrderMailer.with(order: @order).edit_order_email.deliver_later
            flash[:notice] = "Your order was successfully updated"
            redirect_to @order
        else
            render 'edit'
        end
    end
    def destroy
      @order = Order.find(params[:id])
      OrderMailer.with(order: @order).delete_order_email.deliver_later
      @order.destroy
      flash[:notice] = "Order successfully deleted"
      redirect_to root_path
  end

  
    private
  
    def order_params
      params.require(:order).permit(:name, :email, :address, :phone, :message)
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end
    def create
      @user = User.find_by(email: params[:email])
      if @user.present?
        # send mail
        PasswordMailer.with(user: @user).reset.deliver_later
        # deliver_later is provided by ActiveJob
      end
      redirect_to root_path, notice: 'Please check your email to reset the password'
    end
    def edit
      # finds user with a valid token
      @user = User.find_signed!(params[:token], purpose: 'password_reset')
      rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to sign_in_path, alert: 'Your token has expired. Please try again.'
    end
    def update
      # updates user's password
      @user = User.find_signed!(params[:token], purpose: 'password_reset')
      if @user.update(password_params)
        redirect_to sign_in_path, notice: 'Your password was reset successfully. Please sign in'
      else
        render :edit
      end
    end
    private
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end

end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!

    def edit
    end
    def update
      # update user password
      if Current.user.update(password_params)
        redirect_to root_path, notice: 'Password Updated'
      else
        render :edit
      end
    end
    private
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            WelcomeUserMailer.with(user: @user).welcome_user_email.deliver_now
            # stores saved user id in a session
              session[:user_id] = @user.id
              redirect_to root_path, notice: 'Successfully created account'
        else
            render :new
        end
    end
    
    private
    def user_params
      # strong parameters
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
      user = User.find_by(email: params[:email])
      # finds existing user, checks to see if user can be authenticated
      if user.present? && user.authenticate(params[:password])
      # sets up user.id sessions
        session[:user_id] = user.id
        redirect_to root_path, notice: 'Logged in successfully'
      else
        flash.now[:alert] = 'Invalid email or password'
        render :new
      end
    end
    def destroy
      # deletes user session
      session[:user_id] = nil
      redirect_to root_path, notice: 'Logged Out'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
      end
      def show
        @user = User.find(params[:id])
      end
  
      def edit
        #byebug
        @user = User.find(params[:id])
      end
      def update        
          @user = User.find(params[:id])
          if @user.update(order_params)
              #byebug
              #OrderMailer.with(order: @order).new_order_email.deliver_later
              flash[:notice] = "Your user was successfully updated"
              redirect_to @user
          else
              render 'edit'
          end
      end
      def destroy
        @user = User.find(params[:id])
        #OrderMailer.with(order: @order).delete_order_email.deliver_later
        @user.destroy
        flash[:notice] = "User successfully deleted"
        redirect_to root_path
    end
  
    
      private
    
      def order_params
        params.require(:order).permit(:name, :email, :address, :phone, :message)
      end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderAuthEmail</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/orders/edit.html.erb
<h1>Edit an order</h1>
  
  <%= form_with(model: @order, local: true)  do |f| %>
    <p> 
    <%= f.label :name %><br/> 
    <%= f.text_field :name %>
  </p>
  <p> 
    <%= f.label :email %><br/> 
    <%= f.email_field :email %>
  </p>
  <p> 
    <%= f.label :address %><br/> 
    <%= f.text_field :address %>
  </p>
  <p> 
    <%= f.label :phone %><br/> 
    <%= f.text_field :phone %>
  </p>    
  <p>
    <%= f.label :message %><br/> 
    <%= f.text_area :message %> 
  </p>
  <p>
    <%= f.submit %> 
  </p>
  <% end %>

app/views/orders/index.html.erb
<% @orders.each do |order| %>
    <ul>
    <li> Name: <%= order.name %> </li>
    <li> Email: <%= order.email %> </li>
    <li> Address: <%= order.name %> </li>
    <li> Phone: <%= order.phone %> </li>
    <li> Message: <%= order.message %> </li>
    <li><%= link_to 'View', order_path(order)%> | 
        <%= link_to 'Edit', edit_order_path(order)%> |
        <%= link_to 'Delete', order_path(order), method: :delete %> </li>
    </ul>
<% end %>
<%= link_to 'New Order', new_order_path %>
<%= link_to 'Home', root_path %>

app/views/orders/new.html.erb
<h1>Create a new order</h1>
<%= form_with scope: :order, url: orders_path, local: true do |f| %>
  <p> 
    <%= f.label :name %><br/> 
    <%= f.text_field :name %>
  </p>
  <p> 
    <%= f.label :email %><br/> 
    <%= f.email_field :email %>
  </p>
  <p> 
    <%= f.label :address %><br/> 
    <%= f.text_field :address %>
  </p>
  <p> 
    <%= f.label :phone %><br/> 
    <%= f.text_field :phone %>
  </p>    
  <p>
    <%= f.label :message %><br/> 
    <%= f.text_area :message %> 
  </p>
  <p>
    <%= f.submit %> 
  </p>
<% end %>

<%= link_to 'Cancel', root_path %>

app/views/orders/show.html.erb
<ul>
  <li> Name: <%= @order.name %> </li>
  <li> Email: <%= @order.email %> </li>
  <li> Address: <%= @order.name %> </li>
  <li> Phone: <%= @order.phone %> </li>
  <li> Message: <%= @order.message %> </li>
</ul>
<%= link_to 'Home', root_path %> | 
<%= link_to 'Orders', orders_path %>|
<%= link_to 'New Order', new_order_path %>

app/views/password_resets/edit.html.erb
<h1>Reset your password?</h1>
<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |f| %>
  <p>
  <%= f.label 'password:' %><br />
  <%= f.password_field :password %>
  </p>
  <p>
  <%= f.label 'password_confirmation:' %><br />
  <%= f.password_field :password_confirmation %>
  </p>
  <p>
  <%= f.submit 'Reset Password' %>
  </p>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>
<%= form_with url: password_reset_path do |f| %>
  <p>
  <%= f.label 'email:' %><br />
  <%= f.text_field :email %>
  </p>
  <p>
  <%= f.submit 'Reset Password' %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit an user</h1>
  
<%= form_with(model: @user, local: true)  do |f| %>
<p> 
  <%= f.label :email %><br/> 
  <%= f.email_field :email %>
</p>
<p>
  <%= f.submit %> 
</p>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <ul>
    <li> Email: <%= user.email %> </li>
    
    <li><%= link_to 'View', user_path(user)%> | 
        <%= link_to 'Edit', edit_user_path(user)%> |
        <%= link_to 'Delete', user_path(user), method: :delete %> </li>
    </ul>
<% end %>
<%= link_to 'New Order', new_order_path %>
<%= link_to 'Home', root_path %>

app/views/users/show.html.erb
<ul>
  <li> Name: <%= @user.email %> </li>
</ul>
<%= link_to 'Home', root_path %> | 
<%= link_to 'Orders', orders_path %>| 
<%= link_to 'New Order', new_order_path %>

app/views/welcome/home.html.erb
Welcome Home Page

<h2> Place an order: <%= link_to 'Place an order', new_order_path %></h2>

<h2> View orders: <%= link_to 'Orders', orders_path %></h2>
<h2> View users: <%= link_to 'Users', users_path %></h2>

<% if Current.user %>
Logged in as: <%= Current.user.email %><br>
<%= link_to 'Edit Password', edit_password_path %>
<%= button_to 'Logout', logout_path, method: :delete %>
<% else %>
<%= link_to 'Sign Up', sign_up_path %>
or
<%= link_to 'Login', sign_in_path %>
<% end %>